// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// HashPassword
RawVector HashPassword(CharacterVector passwd, size_t maxmem, double maxmemfrac, double maxtime);
RcppExport SEXP scrypt_HashPassword(SEXP passwdSEXP, SEXP maxmemSEXP, SEXP maxmemfracSEXP, SEXP maxtimeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type passwd(passwdSEXP );
        Rcpp::traits::input_parameter< size_t >::type maxmem(maxmemSEXP );
        Rcpp::traits::input_parameter< double >::type maxmemfrac(maxmemfracSEXP );
        Rcpp::traits::input_parameter< double >::type maxtime(maxtimeSEXP );
        RawVector __result = HashPassword(passwd, maxmem, maxmemfrac, maxtime);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// VerifyPassword
bool VerifyPassword(RawVector hash, CharacterVector passwd);
RcppExport SEXP scrypt_VerifyPassword(SEXP hashSEXP, SEXP passwdSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< RawVector >::type hash(hashSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type passwd(passwdSEXP );
        bool __result = VerifyPassword(hash, passwd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
