# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hash a password
#'
#' @param passwd password to hash
#' @param maxmemc max memory percent (default 0.1)
#' @param maxtime max cpu time (default 1.0)
#' @return base64 encoded hash
#' @examples
#' \dontrun{
#'
#' # Hash password using default parameters
#' HashPassword('passw0rd')
#'
#' # Hash password with custom parameters
#' HashPassword('passw0rd', maxmem=.25, maxtime=5.0)
#'
#' }
#' @seealso \code{\link{VerifyPassword}}
#' @export
HashPassword <- function(passwd, maxmem = 0.1, maxtime = 1.0) {
    .Call('scrypt_HashPassword', PACKAGE = 'scrypt', passwd, maxmem, maxtime)
}

#' Verify a hashed password
#'
#' @param hash base64 hash to verify
#' @param passwd password to verify
#' @return
#' TRUE if password matches hash, otherwise FALSE
#' @examples
#' \dontrun{
#'
#' # Hash password using default parameters
#' hashed <- HashPassword('password')
#'
#' VerifyPassword(hashed, "bad password");
#' FALSE
#' 
#' VerifyPassword(hashed, "password")
#' TRUE
#' 
#' }
#' @seealso {
#' \code{\link{HashPassword}}
#' }
#' @export
VerifyPassword <- function(hash, passwd) {
    .Call('scrypt_VerifyPassword', PACKAGE = 'scrypt', hash, passwd)
}

#' @useDynLib scrypt
#' @export
Crypt <- function(passwd, salt, n, r, p, length = 64L) {
    .Call('scrypt_Crypt', PACKAGE = 'scrypt', passwd, salt, n, r, p, length)
}

