# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Encrypt <- function(input, passwd, maxmem = 0L, maxmemfrac = 0.1, maxtime = 1.0) {
    .Call('scrypt_Encrypt', PACKAGE = 'scrypt', input, passwd, maxmem, maxmemfrac, maxtime)
}

Decrypt <- function(input, passwd) {
    .Call('scrypt_Decrypt', PACKAGE = 'scrypt', input, passwd)
}

HashPassword <- function(passwd, maxmem = 0L, maxmemfrac = 0.1, maxtime = 1.0) {
    .Call('scrypt_HashPassword', PACKAGE = 'scrypt', passwd, maxmem, maxmemfrac, maxtime)
}

VerifyPassword <- function(hash, passwd) {
    .Call('scrypt_VerifyPassword', PACKAGE = 'scrypt', hash, passwd)
}

Crypt <- function(passwd, salt, n, r, p, length = 64L) {
    .Call('scrypt_Crypt', PACKAGE = 'scrypt', passwd, salt, n, r, p, length)
}

